/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class studs_group_in_screencaster_device_Native */

#ifndef _Included_studs_group_in_screencaster_device_Native
#define _Included_studs_group_in_screencaster_device_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     studs_group_in_screencaster_device_Native
 * Method:    haveRoot
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_studs_group_in_screencaster_device_Native_haveRoot
  (JNIEnv *, jclass);

/*
 * Class:     studs_group_in_screencaster_device_Native
 * Method:    getFBPortions
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_studs_group_in_screencaster_device_Native_getNumberOfPortions
  (JNIEnv *, jclass, jstring);

/*
 * Class:     studs_group_in_screencaster_device_Native
 * Method:    getCurrent
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_studs_group_in_screencaster_device_Native_getCurrent
  (JNIEnv *, jclass, jstring);

/*
 * Class:     studs_group_in_screencaster_device_Native
 * Method:    destroySharedMemory
 * Signature: (Ljava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_studs_group_in_screencaster_device_Native_destroySharedMemory
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     studs_group_in_screencaster_device_Native
 * Method:    getFBPortion
 * Signature: (Ljava/lang/String;I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_studs_group_in_screencaster_device_Native_getFBPortion
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
